---
- name: Install certbot package(s)
  apt:
    pkg: certbot
    state: latest
    update_cache: yes
    default_release: "{{ certbot_default_release }}"

- name: Create Certbot configuration directory
  file:
    path: "{{ certbot_config_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Certbot accounts directory
  file:
    path: "{{ certbot_config_directory }}/accounts"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create account directory tree for server
  file:
    path: "{{ certbot_config_directory }}/accounts/{{ certbot_server_url|regex_replace('^https?://(.+)/?', '\\1') }}"
    state: directory
    owner: root
    group: root
    mode: 0700
    recurse: yes
